apiVersion: minecraft.hsmade.com/v1
kind: OperatorConfig
metadata:
  name: test
  namespace: minecraft
spec:
  server-jars-pvc: server-jars
  mod-jars-pvc: mod-jars
  servers-pv:
    spec:
      accessModes:
        - ReadWriteOnce
      capacity:
        storage: 1Gi
      hostPath:
        path: /srv/minecraft/servers
      persistentVolumeReclaimPolicy: Retain
      storageClassName: microk8s-hostpath
      volumeMode: Filesystem
  init-container-image: busybox
---
apiVersion: minecraft.hsmade.com/v1
kind: Server
metadata:
  name: test-1
  namespace: minecraft
spec:
  image: adoptopenjdk:8-jre-hotspot
  enabled: true
  maxMemoryMB: 1024
  initMemoryMB: 1024
  server-version: "forge-1.12.2"
  mod-jars:
    - cfm-6.3.0-mc1.12.2.jar
  idleTimeoutSeconds: 10
  properties:
    motd: Abc
    gamemode: creative
    difficulty: peaceful
    spawn-animals: "false"
    spawn-npcs: "true"
    spawn-monsters: "true"
---
apiVersion: minecraft.hsmade.com/v1
kind: Server
metadata:
  name: test-2
  namespace: minecraft
spec:
  image: adoptopenjdk:8-jre-hotspot
  enabled: true
  maxMemoryMB: 1024
  initMemoryMB: 1024
  server-version: "vanilla-1.16.5"
  idleTimeoutSeconds: 10
  properties:
    motd: mijn server
    gamemode: creative
    difficulty: peaceful
    spawn-animals: "true"
    spawn-npcs: "true"
    spawn-monsters: "true"
---
apiVersion: minecraft.hsmade.com/v1
kind: Server
metadata:
  name: test-3
  namespace: minecraft
spec:
  image: adoptopenjdk:8-jre-hotspot
  enabled: false
  maxMemoryMB: 1024
  initMemoryMB: 1024
  server-version: "vanilla-1.16.5"
  hostPort: 25699
  idleTimeoutSeconds: 10
  properties:
    motd: mijn server - uit
    gamemode: creative
    difficulty: peaceful
    spawn-animals: "true"
    spawn-npcs: "true"
    spawn-monsters: "true"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-server-jars
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /srv/minecraft/jars/server
  persistentVolumeReclaimPolicy: Retain
  storageClassName: microk8s-hostpath
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: server-jars
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath
  volumeMode: Filesystem
  volumeName: minecraft-server-jars
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-mod-jars
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /srv/minecraft/jars/mods
  persistentVolumeReclaimPolicy: Retain
  storageClassName: microk8s-hostpath
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mod-jars
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath
  volumeMode: Filesystem
  volumeName: minecraft-mod-jars
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: operator
  namespace: minecraft-operator-system
  annotations:
    kubernetes.io/ingress.class: traefik-internal
    traefik.ingress.kubernetes.io/router.entrypoints: int
    traefik.ingress.kubernetes.io/router.priority: "2"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt
spec:
  rules:
    - host: minecraft-operator.kiezelsteen18.nl
      http:
        paths:
          - backend:
              service:
                name: minecraft-operator-controller-manager-web-ui
                port:
                  name: http
            path: /
            pathType: Prefix
