apiVersion: minecraft.hsmade.com/v1
kind: Server
metadata:
  name: test-on
  namespace: minecraft
spec:
  hostPath: /tmp/minecraft-test/
  image: adoptopenjdk:8-jre-hotspot
  enabled: true
  flavor: vanilla
  version: 1.16.5
  maxMemoryMB: 1024
  initMemoryMB: 1024
  jarSite: "https://hsmade.com/minecraft"
  nodePort: true
  idleTimeoutSeconds: 10
  properties:
    motd: mijn server
    gamemode: creative
    difficulty: peaceful
    spawn-animals: true
    spawn-npcs: true
    spawn-monsters: true
---
apiVersion: minecraft.hsmade.com/v1
kind: Server
metadata:
  name: test-off
  namespace: minecraft
spec:
  hostPath: /tmp/minecraft-test/
  image: adoptopenjdk:8-jre-hotspot
  enabled: false
  flavor: vanilla
  version: 1.14.4
  maxMemoryMB: 1024
  initMemoryMB: 1024
  jarSite: "https://hsmade.com/minecraft"
  hostPort: 25699
  idleTimeoutSeconds: 10
  properties:
    motd: mijn server - uit
    gamemode: creative
    difficulty: peaceful
    spawn-animals: true
    spawn-npcs: true
    spawn-monsters: true
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: operator
  namespace: minecraft-operator-system
  annotations:
    kubernetes.io/ingress.class: traefik-internal
    traefik.ingress.kubernetes.io/router.entrypoints: int
    traefik.ingress.kubernetes.io/router.priority: "2"
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt

spec:
  rules:
    - host: minecraft-operator.kiezelsteen18.nl
      http:
        paths:
          - backend:
              serviceName: minecraft-operator-controller-manager-web-ui
              servicePort: 8082
            path: /
