# permissions for end users to view minecrafts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minecraft-viewer-role
rules:
- apiGroups:
  - hsmade.com
  resources:
  - minecrafts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hsmade.com
  resources:
  - minecrafts/status
  verbs:
  - get
