# permissions for end users to edit mods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mod-editor-role
rules:
- apiGroups:
  - minecraft.hsmade.com
  resources:
  - mods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - minecraft.hsmade.com
  resources:
  - mods/status
  verbs:
  - get
