# permissions for end users to view mods.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mod-viewer-role
rules:
- apiGroups:
  - minecraft.hsmade.com
  resources:
  - mods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - minecraft.hsmade.com
  resources:
  - mods/status
  verbs:
  - get
