apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: minecraft-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Installs Minecraft servers
  displayName: Minecraft Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - minecraft
  links:
  - name: Minecraft Operator
    url: https://minecraft-operator.domain
  maintainers:
  - email: wim@hsmade.com
    name: Wim Fournier
  maturity: alpha
  provider:
    name: hsmade
  version: 0.0.0
