---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minecraft-{{ .Release.Name }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "{{ .Values.storage.path }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-{{ .Release.Name }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
